services:
  # openpcdet-pixi:
  #   build:
  #     dockerfile: openpcdet.Dockerfile
  #   image: openpcdet_pixi:latest
  #   container_name: velodyne_openpcdet_pixi 
  #     # - ./external:/external
  #   # command: ["bash"]
  #   # command: bash -c "pixi install -e pifenet && tail -f /dev/null"
  #   command: bash -c "tail -f /dev/null"
  #   stdin_open: true # docker run -i
  #   runtime: nvidia
  #   network_mode: host
  #   privileged: true
  #   environment:
  #     # Allows graphical programs in the container.
  #     - DISPLAY=${DISPLAY}
  #     - QT_X11_NO_MITSHM=1
  #     - NVIDIA_DRIVER_CAPABILITIES=all
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities:
  #             - gpu
  #   volumes:
  #     - ./packages/ros2_numpy:/project/packages/ros2_numpy:cached
  #     - ./src/pcdet_ros2:/project/src/pcdet_ros2:cached
  #     - ./src/openpcdet:/project/src/openpcdet:cached
  #     - ./src/lidar:/project/src/lidar:cached

  #     - ./pixi_confs/pixi.toml:/project/pixi.toml:cached
  #     - ./pixi_confs/ros2_numpy.pixi.toml:/project/packages/ros2_numpy/pixi.toml:cached
  #     - ./pixi_confs/pcdet_ros2.pixi.toml:/project/packages/pcdet_ros2/pixi.toml:cached
  #     # - ./pixi_confs/openpcdet.pyproject.toml:/project/src/openpcdet/pyproject.toml:cached
  #     # - ${PWD}/data/pretrained-models/:/project/data/pretrained-models
  #     - ./data/:/project/data/
  #     - ../datos/ros1_rosbags/:/project/data/ros1_rosbags/:cached
      
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #     - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
  #   develop:
  #     # Create a `watch` configuration to update the app
  #     # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
  #     watch:
  #       # Sync the working directory with the `/app` directory in the container
  #       - action: sync
  #         path: .
  #         target: /app
  #         # Exclude the project virtual environment — it could be for a
  #         # different platform in the container
  #         ignore:
  #           - .venv/

  #       # Rebuild the image if dependencies change by checking uv.lock
  #       - action: rebuild
  #         path: ./pyproject.toml

  openpcdet-prebuilt:
    build:
      dockerfile: cu116.krz.Dockerfile
    image: openpcdet:latest
    container_name: velodyne_openpcdet
      # - ./external:/external
    # command: ["bash"]
    # command: bash -c "pixi install -e pifenet && tail -f /dev/null"
    command: bash -c "tail -f /dev/null"
    stdin_open: true # docker run -i
    runtime: nvidia
    ipc: host
    network_mode: host
    pid: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    volumes:
      - ./src/lidar:/OpenPCDet/src/lidar:cached
      # - ${PWD}/.pixi/pifenet.pixi.toml:/workspaces/pifenet/pixi.toml
      - ../datos/kitti/training:/OpenPCDet/data/original-kitti/training
      - ../datos/kitti/testing:/OpenPCDet/data/original-kitti/testing
      - ../datos/kitti/ImageSets:/OpenPCDet/data/original-kitti/ImageSets
      - ../datos/kitti/gt_database:/OpenPCDet/data/original-kitti/gt_database:cached
      # # # db pickle files
      - ../datos/kitti/db_infos:/OpenPCDet/data/original-kitti/db_infos:cached

      - ../datos/reduced-kitti:/OpenPCDet/data/reduced-kitti:cached
      - ../datos/reduced-kitti/gt_database:/OpenPCDet/data/reduced-kitti/gt_database:cached
      - ../datos/reduced-kitti/db_infos:/OpenPCDet/data/reduced-kitti/db_infos/:cached

      - ./data/npy_data:/OpenPCDet/data/npy_data/:cached
      - ../datos/ros1_rosbags/:/OpenPCDet/data/ros1_rosbags/:cached
      - ../datos/pretrained-models/:/OpenPCDet/data/pretrained-models:cached
      - ../datos/confs/parta2-anchor.yaml:/OpenPCDet/data/confs/parta2-anchor.yaml:cached
      - ../datos/output:/OpenPCDet/output:cached
      - ../datos/output_runs:/OpenPCDet/output_runs:cached
      # - ..datos/interpolated-kitti/:/OpenPCDet/data/interpolated-kitti:ro
      - /media/cristobalmedina/SAMSUNG/memoria/interpolated-kitti/:/OpenPCDet/data/interpolated-kitti:ro
      - ./src/lidar/tools/fixed_kitti_dataset.py:/OpenPCDet/pcdet/datasets/kitti/fixed_kitti_dataset.py:cached

      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./pyproject.toml
    environment:
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      # - ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  velodyne_ros:
    build:
      dockerfile: ros2.pixi.Dockerfile
    image: velodyne_ros2:latest
    container_name: velodyne_ros2
    ipc: host
    network_mode: host
    pid: host
    command: bash -c "tail -f /dev/null && pixi run rviz"
    # Needed to display graphical applications
    privileged: true
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      # - ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - ./data/ros2_bags:/app/data/ros2_bags:cached
      - ./data/interpolated_bags:/app/data/interpolated_bags:cached
      - ./data/config_files/rviz/:/app/data/config_files/rviz/:cached
      - ./data/config_files/interpolation/:/app/data/config_files/interpolation/:cached
      - ../datos/kitti/:/app/data/kitti:cached
      - ../datos/reduced-kitti/:/app/data/reduced-kitti:cached
      - ../datos/output_runs/:/app/data/output_runs:ro
      # - ../datos/interpolated-kitti/:/app/data/output/interpolated-kitti:cached
      - /media/cristobalmedina/SAMSUNG/memoria/interpolated-kitti/:/app/data/output/interpolated-kitti:cached

      # - ./packages/dynamic_lidar_interpolation:/app/packages/dynamic_lidar_interpolation:cached
      - ./packages/pointcloud_utils/scripts:/app/packages/pointcloud_utils/scripts:cached
      - ./packages/pointcloud_utils/config/:/app/packages/pointcloud_utils/config:cached
      - ./pixi_confs/ros2.pixi.toml:/app/pixi.toml:cached
      - ./scripts/batch_downsample.sh:/app/scripts/batch_downsample.sh:cached
      - ./pixi_confs/dynamic_lidar_interpolation.pixi.toml:/app/packages/dynamic_lidar_interpolation/pixi.toml:cached
      # - ./pixi_confs/pointcloud_utils.pixi.toml:/app/packages/pointcloud_utils/pixi.toml:cached
      - ./pixi_confs/ros2_numpy.pixi.toml:/app/packages/ros2_numpy/pixi.toml:cached
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
    tty: true

  # velodyne_ros_u18:
  #   build:
  #     dockerfile: ros2.ubuntu18.pixi.Dockerfile
  #   image: velodyne_u18_ros2:latest
  #   container_name: velodyne_u18_ros2
  #   network_mode: "host"
  #   ipc: host
  #   command: bash -c "tail -f /dev/null"
  #   # Needed to display graphical applications
  #   privileged: true
  #   environment:
  #     # Allows graphical programs in the container.
  #     - DISPLAY=${DISPLAY}
  #     - QT_X11_NO_MITSHM=1
  #     - NVIDIA_DRIVER_CAPABILITIES=all
  #   volumes:
  #     - ${PWD}/src/ros2_numpy:/app/ros2_numpy:cached
  #     - ${PWD}/src/pcdet_ros2:/app/pcdet_ros2:cached
  #     - ${PWD}/.pixi/ros2.pixi.toml:/app/pixi.toml
  #     # Allows graphical programs in the container.
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #     - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
  #   tty: true