#!/usr/bin/env bash
# run_full_pipeline.sh — Master pipeline: downsample → infos → interpolate → evaluate → report
#
# Executes all steps sequentially and organises outputs under:
#
#   <host>/../datos/output_runs/<TIMESTAMP>/    (= /OpenPCDet/output_runs/<TIMESTAMP>/ in openpcdet)
#     raw_results/
#       desempeno_offline/
#         original/        ← eval results for original KITTI
#         downsampled/     ← eval results for reduced-kitti
#         interpolated/    ← eval results per interpolation config
#         detections/      ← save_detections.py output (per dataset/model)
#       desempeno_online/  ← run_realtime_eval.sh output
#     latex/
#       desempeno_offline/ ← AP + recall tables
#       desempeno_online/  ← aggregated realtime results
#
# Container volume layout (from compose.yml):
#
#   velodyne_ros2 (CONTAINER_VELODYNE):
#     ../datos/kitti/                          → /app/data/kitti
#     ../datos/reduced-kitti/                  → /app/data/reduced-kitti
#     <ext>/interpolated-kitti/                → /app/data/output/interpolated-kitti  (rw)
#     ./data/config_files/interpolation/       → /app/data/config_files/interpolation/
#     scripts baked into image                 → /app/packages/pointcloud_utils/scripts/
#
#   velodyne_openpcdet (CONTAINER_OPENPCDET):
#     ../datos/kitti/training                  → /OpenPCDet/data/original-kitti/training
#     ../datos/kitti/testing                   → /OpenPCDet/data/original-kitti/testing
#     ../datos/kitti/ImageSets                 → /OpenPCDet/data/original-kitti/ImageSets
#     ../datos/kitti/gt_database               → /OpenPCDet/data/original-kitti/gt_database
#     ../datos/kitti/db_infos                  → /OpenPCDet/data/original-kitti/db_infos
#     ../datos/reduced-kitti/                  → /OpenPCDet/data/reduced-kitti           (rw)
#     ../datos/reduced-kitti/gt_database       → /OpenPCDet/data/reduced-kitti/gt_database
#     ../datos/reduced-kitti/db_infos          → /OpenPCDet/data/reduced-kitti/db_infos/
#     <ext>/interpolated-kitti/                → /OpenPCDet/data/interpolated-kitti      (ro)
#     ../datos/pretrained-models/              → /OpenPCDet/data/pretrained-models
#     ../datos/output_runs/                    → /OpenPCDet/output_runs
#     ./src/lidar/                             → /OpenPCDet/src/lidar
#
# KITTI data structure expected/created by this pipeline:
#
#   reduced-kitti/
#     training/
#       velodyne/     ← downsampled .bin files (written by step 1)
#       calib/        ← symlink → original-kitti/training/calib   (created by step 2)
#       image_2/      ← symlink → original-kitti/training/image_2  (created by step 2)
#       label_2/      ← symlink → original-kitti/training/label_2  (created by step 2)
#       planes/       ← symlink → original-kitti/training/planes   (if it exists)
#     testing/
#       calib/        ← symlink → original-kitti/testing/calib     (created by step 2)
#       image_2/      ← symlink → original-kitti/testing/image_2   (created by step 2)
#       velodyne/     ← symlink → original-kitti/testing/velodyne  (created by step 2)
#     ImageSets/      ← symlink → original-kitti/ImageSets         (created by step 2)
#     kitti_infos_train.pkl    )
#     kitti_infos_val.pkl      )  generated by create_kitti_infos (step 2)
#     kitti_infos_trainval.pkl )
#     kitti_infos_test.pkl     )
#     kitti_dbinfos_train.pkl  )
#
#   interpolated-kitti/<cfg_name>/
#     training/
#       velodyne/     ← interpolated .bin files (written by step 3)
#
# Usage:
#   ./run_full_pipeline.sh [--skip-downsample] [--skip-infos] [--skip-interp]
#                          [--skip-offline] [--skip-online]
#                          [--single-model M] [--single-config C]
#                          [--rate HZ] [--max-frames N]
set -euo pipefail

# ─── Containers ──────────────────────────────────────────────────────────────
CONTAINER_VELODYNE="${CONTAINER_VELODYNE:-velodyne_ros2}"
CONTAINER_OPENPCDET="${CONTAINER_OPENPCDET:-velodyne_openpcdet}"

# ─── Paths inside the velodyne container ─────────────────────────────────────
VEL_SCRIPTS="/app/packages/pointcloud_utils/scripts"
VEL_INTERP_SCRIPT="/app/packages/dynamic_lidar_interpolation/scripts/interpolate_bin_batch.py"
VEL_INTERP_CONFIG_DIR="/app/data/config_files/interpolation/final"
VEL_KITTI_VELODYNE="/app/data/kitti/"
VEL_KITTI_REDUCED="/app/data/reduced-kitti"
VEL_KITTI_INTERP_BASE="/app/data/output/interpolated-kitti"   # read-write

# ─── Paths inside the openpcdet container ────────────────────────────────────
OPC_ROOT="/OpenPCDet"
OPC_DATA="${OPC_ROOT}/data"
OPC_TOOLS="${OPC_ROOT}/src/lidar/tools"
OPC_BATCH="${OPC_TOOLS}/batch_evaluation"

OPC_KITTI_DATA="${OPC_DATA}/original-kitti"
OPC_KITTI_VELODYNE="${OPC_KITTI_DATA}/training/velodyne"   # original 64-beam bins

OPC_KITTI_REDUCED="${OPC_DATA}/reduced-kitti"
OPC_KITTI_REDUCED_VELODYNE="${OPC_KITTI_REDUCED}/training/velodyne"  # downsampled bins

OPC_KITTI_INTERP_BASE="${OPC_DATA}/interpolated-kitti"     # read-only
OPC_PRETRAINED="${OPC_DATA}/pretrained-models"
OPC_RESULTS_BASE="${OPC_ROOT}/output_runs"

# Dataset-info configs (relative to OPC_ROOT, used with python3 -m)
OPC_CFG_ORIGINAL="src/lidar/tools/cfgs/dataset_configs/create_dataset_info_original_kitti_dataset.yaml"
OPC_CFG_REDUCED="src/lidar/tools/cfgs/dataset_configs/create_dataset_info_downsampled_kitti_dataset.yaml"

# Minimum free space in GB required before starting
MIN_FREE_GB=50

# ─── Result root ─────────────────────────────────────────────────────────────
# Host path mirrors the ../datos/output_runs → /OpenPCDet/output_runs mount.
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
RESULTS_HOST="$(cd "$(dirname "$0")/.." && pwd)/datos/output_runs/${TIMESTAMP}"
RESULTS_OPC="${OPC_RESULTS_BASE}/${TIMESTAMP}"

OFFLINE_RAW="${RESULTS_OPC}/raw_results/desempeno_offline"
ONLINE_RAW="${RESULTS_OPC}/raw_results/desempeno_online"
OFFLINE_LATEX="${RESULTS_OPC}/latex/desempeno_offline"
ONLINE_LATEX="${RESULTS_OPC}/latex/desempeno_online"

# ─── CLI flags ────────────────────────────────────────────────────────────────
SKIP_DOWNSAMPLE=false
SKIP_INFOS=false
SKIP_INTERP=false
SKIP_OFFLINE=false
SKIP_ONLINE=false
SINGLE_MODEL=""
SINGLE_CONFIG=""
PUBLISH_RATE=10.0
MAX_FRAMES=500
WARMUP_FRAMES=10

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-downsample) SKIP_DOWNSAMPLE=true; shift ;;
        --skip-infos)      SKIP_INFOS=true;      shift ;;
        --skip-interp)     SKIP_INTERP=true;     shift ;;
        --skip-offline)    SKIP_OFFLINE=true;    shift ;;
        --skip-online)     SKIP_ONLINE=true;     shift ;;
        --single-model)    SINGLE_MODEL="$2";    shift 2 ;;
        --single-config)   SINGLE_CONFIG="$2";   shift 2 ;;
        --rate)            PUBLISH_RATE="$2";    shift 2 ;;
        --max-frames)      MAX_FRAMES="$2";      shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ─── Models ──────────────────────────────────────────────────────────────────
declare -A MODELS
MODELS[parta2_anchor]="parta2_anchor.yaml PartA2_7940.pth"
MODELS[pointpillar]="pointpillar.yaml pointpillar_7728.pth"
MODELS[pointrcnn_iou]="pointrcnn_iou.yaml pointrcnn_iou_7875.pth"
MODELS[pv_rcnn]="pv_rcnn.yaml pv_rcnn_8369.pth"
MODELS[second]="second.yaml second_7862.pth"
MODELS[second_iou]="second_iou.yaml second_iou7909.pth"

# ─── Helpers (same pattern as run_realtime_eval.sh) ───────────────────────────
log()  { echo "[$(date +%H:%M:%S)] $*"; }
step() { echo; echo "════════════════════════════════════════════════════════"; \
         echo " $*"; echo "════════════════════════════════════════════════════════"; }


# ─── Step 0: Storage check ───────────────────────────────────────────────────
# Check both mounts: openpcdet (eval outputs) and the external drive where
# interpolated datasets are written (velodyne container, read-write mount).
check_storage() {
    log "Checking available storage..."

    local opc_free
    opc_free=$(docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "df -BG '${OPC_DATA}' | awk 'NR==2{gsub(\"G\",\"\",\$4); print \$4}'")
    log "  [openpcdet] ${OPC_DATA}: ${opc_free} GB free"

    local vel_free
    vel_free=$(docker exec "${CONTAINER_VELODYNE}" bash -c \
        "df -BG '${VEL_KITTI_INTERP_BASE}' | awk 'NR==2{gsub(\"G\",\"\",\$4); print \$4}'")
    log "  [velodyne]  ${VEL_KITTI_INTERP_BASE}: ${vel_free} GB free"

    log "  Minimum required: ${MIN_FREE_GB} GB in each location."
    if [[ "${opc_free}" -lt "${MIN_FREE_GB}" ]]; then
        echo "ERROR: Insufficient storage in openpcdet (${opc_free} GB < ${MIN_FREE_GB} GB)." >&2
        exit 1
    fi
    # if [[ "${vel_free}" -lt "${MIN_FREE_GB}" ]]; then
    #     echo "ERROR: Insufficient storage on external drive (${vel_free} GB < ${MIN_FREE_GB} GB)." >&2
    #     exit 1
    # fi
    log "Storage OK."
}

# ─── Step 1: Downsample KITTI 64→16 ─────────────────────────────────────────
# Output goes to training/velodyne/ so the directory tree matches what
# fixed_kitti_dataset.py and setupandruntest.py expect.
run_downsample() {
    step "Step 1: Downsampling KITTI 64-beam → 16-beam (VLP-16 simulation)"
    docker exec "${CONTAINER_VELODYNE}" bash -c \
        "mkdir -p '${VEL_KITTI_REDUCED}/training/velodyne' && \
         pixi run python3 ${VEL_SCRIPTS}/downsample_64_to_16.py \
             ${VEL_KITTI_VELODYNE}/training/velodyne ${VEL_KITTI_REDUCED}/training/velodyne --batch"
    log "Downsampled dataset written to ${VEL_KITTI_REDUCED}/training/velodyne"
    
    docker exec "${CONTAINER_VELODYNE}" bash -c \
        "mkdir -p '${VEL_KITTI_REDUCED}/testing/velodyne' && \
         pixi run python3 ${VEL_SCRIPTS}/downsample_64_to_16.py \
             ${VEL_KITTI_VELODYNE}/testing/velodyne ${VEL_KITTI_REDUCED}/testing/velodyne --batch"
    log "Downsampled dataset written to ${VEL_KITTI_REDUCED}/testing/velodyne"
}

# ─── Step 2: KITTI dataset infos ─────────────────────────────────────────────
# Sets up the directory structure needed by fixed_kitti_dataset, then runs
# create_kitti_infos for both original KITTI (if PKLs are missing) and for
# reduced-kitti (always, since the velodyne data just changed).
# Interpolated datasets reuse the reduced-kitti PKLs via setupandruntest.py.
run_kitti_infos() {
    step "Step 2: KITTI dataset infos"

    # ── 2a. Symlink reduced-kitti auxiliary data → original-kitti ─────────────
    # reduced-kitti/training/velodyne already has the downsampled bins.
    # Everything else (calib, images, labels, ImageSets, testing) comes from
    # original-kitti via symlinks so that fixed_kitti_dataset can find them.
    log "Setting up auxiliary symlinks in reduced-kitti..."
    docker exec "${CONTAINER_OPENPCDET}" bash -c "
        set -e
        R='${OPC_KITTI_REDUCED}'
        O='${OPC_KITTI_DATA}'
        mkdir -p \"\$R/training\" \"\$R/testing\"
        ln -sfn \"\$O/ImageSets\"          \"\$R/ImageSets\"
        ln -sfn \"\$O/training/calib\"     \"\$R/training/calib\"
        ln -sfn \"\$O/training/image_2\"   \"\$R/training/image_2\"
        ln -sfn \"\$O/training/label_2\"   \"\$R/training/label_2\"
        [ -d \"\$O/training/planes\" ] && ln -sfn \"\$O/training/planes\" \"\$R/training/planes\" || true
        ln -sfn \"\$O/testing/calib\"      \"\$R/testing/calib\"
        ln -sfn \"\$O/testing/image_2\"    \"\$R/testing/image_2\"
        ln -sfn \"\$O/testing/velodyne\"   \"\$R/testing/velodyne\"
    "
    log "Auxiliary symlinks ready."

    # ── 2b. Original KITTI infos (skip if PKLs already exist) ─────────────────
    local opc_pkl="${OPC_KITTI_DATA}/kitti_infos_train.pkl"
    local has_pkl
    has_pkl=$(docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "[ -f '${opc_pkl}' ] && echo yes || echo no")
    if [[ "${has_pkl}" == "yes" ]]; then
        log "Original KITTI PKLs found — skipping create_kitti_infos."
    else
        log "Creating dataset infos for original KITTI..."
        docker exec "${CONTAINER_OPENPCDET}" bash -c \
            "cd ${OPC_ROOT} && \
             python3 -m pcdet.datasets.kitti.fixed_kitti_dataset \
                 create_kitti_infos ${OPC_CFG_ORIGINAL}"
        log "Original KITTI infos done."
    fi

    # ── 2c. Reduced-kitti infos (always regenerate after downsampling) ─────────
    log "Creating dataset infos for reduced-kitti..."
    docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "cd ${OPC_ROOT} && \
         python3 -m pcdet.datasets.kitti.fixed_kitti_dataset \
             create_kitti_infos ${OPC_CFG_REDUCED}"
    log "Reduced-kitti infos done."
}

# ─── Step 3: Generate interpolated datasets ───────────────────────────────────
# Calls interpolate_bin_batch.py directly in the velodyne container (no ROS2).
# Both splits are processed independently; a split is skipped if its target
# directory already exists and is non-empty.
# Output layout: <cfg_name>/training/velodyne/ and <cfg_name>/testing/velodyne/
# so that setupandruntest.py can find lidar_root/training/velodyne.
run_interpolation() {
    step "Step 3: Generating interpolated datasets"

    local configs
    configs=$(docker exec "${CONTAINER_VELODYNE}" bash -c \
        "ls '${VEL_INTERP_CONFIG_DIR}'/*.yaml 2>/dev/null | sort")

    if [[ -z "${configs}" ]]; then
        log "WARNING: No interpolation configs found in ${VEL_INTERP_CONFIG_DIR}. Skipping."
        return
    fi

    local train_src="${VEL_KITTI_REDUCED}/training/velodyne"
    local test_src="${VEL_KITTI_REDUCED}/testing/velodyne"

    while IFS= read -r cfg_file; do
        [[ -z "${cfg_file}" ]] && continue
        local cfg_name
        cfg_name=$(basename "${cfg_file}" .yaml)
        [[ -n "${SINGLE_CONFIG}" && "${cfg_name}" != "${SINGLE_CONFIG}" ]] && continue

        local dataset_out="${VEL_KITTI_INTERP_BASE}/${cfg_name}"
        local train_out="${dataset_out}/training/velodyne"
        local test_out="${dataset_out}/testing/velodyne"

        echo "------------------------------------------------------------"
        echo " CONFIG: ${cfg_name}"
        echo "------------------------------------------------------------"

        # Ensure dataset folder exists and copy config there (always)
        docker exec "${CONTAINER_VELODYNE}" bash -c \
            "mkdir -p '${dataset_out}' && cp -f '${cfg_file}' '${dataset_out}/'"

        # Check which splits need processing
        local train_skip test_skip
        train_skip=$(docker exec "${CONTAINER_VELODYNE}" bash -c \
            "[[ -d '${train_out}' && -n \"\$(ls -A '${train_out}' 2>/dev/null)\" ]] \
             && echo yes || echo no")
        test_skip=$(docker exec "${CONTAINER_VELODYNE}" bash -c \
            "[[ -d '${test_out}' && -n \"\$(ls -A '${test_out}' 2>/dev/null)\" ]] \
             && echo yes || echo no")

        if [[ "${train_skip}" == "yes" && "${test_skip}" == "yes" ]]; then
            log "  SKIP: both splits already non-empty for ${cfg_name}"
            continue
        fi

        docker exec "${CONTAINER_VELODYNE}" bash -c \
            "mkdir -p '${dataset_out}/training' '${dataset_out}/testing'"

        if [[ "${train_skip}" != "yes" ]]; then
            log "  [1/2] Interpolating TRAIN split for ${cfg_name}..."
            docker exec "${CONTAINER_VELODYNE}" bash -c \
                "pixi run python3 '${VEL_INTERP_SCRIPT}' \
                    '${train_src}' '${train_out}' --config '${cfg_file}'"
        else
            log "  [1/2] SKIP TRAIN: already non-empty"
        fi

        if [[ "${test_skip}" != "yes" ]]; then
            log "  [2/2] Interpolating TEST split for ${cfg_name}..."
            docker exec "${CONTAINER_VELODYNE}" bash -c \
                "pixi run python3 '${VEL_INTERP_SCRIPT}' \
                    '${test_src}' '${test_out}' --config '${cfg_file}'"
        else
            log "  [2/2] SKIP TEST: already non-empty"
        fi

        log "Done: ${cfg_name}"
    done <<< "${configs}"
}

# ─── Step 4: Offline batch evaluations ───────────────────────────────────────
# Runs in openpcdet container (GPU inference, model configs in src/lidar).
#
# setupandruntest.py expects:
#   --dataset-root  DIR   dir containing PKLs, gt_database, calib, label_2, etc.
#   --image-set-root DIR  dir containing ImageSets/
#   --lidar-root    DIR   dir containing training/velodyne and testing/velodyne
#
# Interpolated datasets reuse reduced-kitti PKLs (dataset_root=OPC_KITTI_REDUCED)
# but point to their own velodyne bins (lidar_root=interp/<cfg_name>).
run_batch_eval() {
    # Args: cfg_subdir  dataset_root  imageset_root  lidar_root  dest_dir  dataset_label
    local cfg_subdir="$1" dataset_root="$2" imageset_root="$3" lidar_root="$4" \
          dest_dir="$5" dataset_label="${6:-$(basename "${lidar_root}")}"

    docker exec "${CONTAINER_OPENPCDET}" bash -c "mkdir -p '${dest_dir}'"

    for MODEL in $(printf '%s\n' "${!MODELS[@]}" | sort); do
        [[ -n "${SINGLE_MODEL}" && "${MODEL}" != "${SINGLE_MODEL}" ]] && continue
        read -r CFG CKPT <<< "${MODELS[$MODEL]}"
        log "  [${dataset_label}] Model: ${MODEL}"
        docker exec "${CONTAINER_OPENPCDET}" bash -c \
            "cd ${OPC_ROOT} && \
             python3 ${OPC_TOOLS}/setupandruntest.py \
                --dataset-root   '${dataset_root}' \
                --image-set-root '${imageset_root}' \
                --lidar-root     '${lidar_root}' \
                --cfg_file ${OPC_TOOLS}/cfgs/kitti_models/${cfg_subdir}/${CFG} \
                --batch_size 1 \
                --ckpt ${OPC_PRETRAINED}/${CKPT}"
        local src="${OPC_ROOT}/output/src/lidar/tools/cfgs/kitti_models/${cfg_subdir}/${MODEL}"
        docker exec "${CONTAINER_OPENPCDET}" bash -c \
            "mkdir -p '${dest_dir}/${dataset_label}' && \
             mv '${src}' '${dest_dir}/${dataset_label}/${MODEL}' 2>/dev/null || true"
    done
}

run_offline_evals() {
    step "Step 4: Offline batch evaluations"
    docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "mkdir -p '${OFFLINE_RAW}/original' '${OFFLINE_RAW}/downsampled' \
                   '${OFFLINE_RAW}/interpolated'"

    # Original KITTI: data_root = imageset_root = lidar_root = OPC_KITTI_DATA
    log "--- Original KITTI ---"
    run_batch_eval "original" \
        "${OPC_KITTI_DATA}" "${OPC_KITTI_DATA}" "${OPC_KITTI_DATA}" \
        "${OFFLINE_RAW}/original" "kitti"

    # Reduced KITTI: data_root = imageset_root = lidar_root = OPC_KITTI_REDUCED
    # (has training/velodyne with downsampled bins, plus symlinks to original aux data)
    log "--- Downsampled (reduced-kitti) ---"
    run_batch_eval "downsampled" \
        "${OPC_KITTI_REDUCED}" "${OPC_KITTI_REDUCED}" "${OPC_KITTI_REDUCED}" \
        "${OFFLINE_RAW}/downsampled" "reduced"

    # Interpolated: PKLs from reduced-kitti, velodyne from interpolated dir.
    log "--- Interpolated datasets ---"
    local configs
    configs=$(docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "ls '${OPC_KITTI_INTERP_BASE}' 2>/dev/null | sort" || true)
    while IFS= read -r cfg_name; do
        [[ -z "${cfg_name}" ]] && continue
        [[ -n "${SINGLE_CONFIG}" && "${cfg_name}" != "${SINGLE_CONFIG}" ]] && continue
        local interp_root="${OPC_KITTI_INTERP_BASE}/${cfg_name}"
        log "  Interpolated config: ${cfg_name}"
        run_batch_eval "interpolated" \
            "${OPC_KITTI_REDUCED}" "${OPC_KITTI_REDUCED}" "${interp_root}" \
            "${OFFLINE_RAW}/interpolated" "${cfg_name}"
    done <<< "${configs}"
}

# ─── Step 5: Save per-frame detection bboxes ─────────────────────────────────
# save_detections.py --bin-dir takes the directory of .bin files directly.
run_save_detections() {
    step "Step 5: Saving per-frame detection results (kitti_inspector compatible)"
    docker exec "${CONTAINER_OPENPCDET}" bash -c "mkdir -p '${OFFLINE_RAW}/detections'"

    local datasets=(
        "original:${OPC_KITTI_VELODYNE}"
        "downsampled:${OPC_KITTI_REDUCED_VELODYNE}"
    )

    local configs
    configs=$(docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "ls '${OPC_KITTI_INTERP_BASE}' 2>/dev/null | sort" || true)
    while IFS= read -r cfg_name; do
        [[ -z "${cfg_name}" ]] && continue
        [[ -n "${SINGLE_CONFIG}" && "${cfg_name}" != "${SINGLE_CONFIG}" ]] && continue
        datasets+=("interp_${cfg_name}:${OPC_KITTI_INTERP_BASE}/${cfg_name}/training/velodyne")
    done <<< "${configs}"

    for entry in "${datasets[@]}"; do
        local label="${entry%%:*}"
        local bin_dir="${entry#*:}"

        for MODEL in $(printf '%s\n' "${!MODELS[@]}" | sort); do
            [[ -n "${SINGLE_MODEL}" && "${MODEL}" != "${SINGLE_MODEL}" ]] && continue
            read -r CFG CKPT <<< "${MODELS[$MODEL]}"
            local out="${OFFLINE_RAW}/detections/${label}/${MODEL}"
            log "  save_detections: ${label} / ${MODEL}"
            docker exec "${CONTAINER_OPENPCDET}" bash -c \
                "cd ${OPC_ROOT} && \
                 python3 ${OPC_BATCH}/save_detections.py \
                    --cfg_file  ${OPC_TOOLS}/cfgs/kitti_models/${CFG} \
                    --ckpt      ${OPC_PRETRAINED}/${CKPT} \
                    --bin-dir   '${bin_dir}' \
                    --output-dir '${out}'" || \
            log "  WARNING: save_detections failed for ${label}/${MODEL}"
        done
    done
}

# ─── Step 6: Online (real-time) evaluation ────────────────────────────────────
# Delegates to run_realtime_eval.sh, which handles its own container orchestration.
# --data-path must be the velodyne-container path to the .bin files (the velodyne
# subdirectory, since run_realtime_eval.sh passes it directly to bin_publisher_node).
run_online_eval() {
    step "Step 6: Online (real-time) evaluation"
    docker exec "${CONTAINER_OPENPCDET}" bash -c "mkdir -p '${ONLINE_RAW}'"

    local args="--output-dir ${ONLINE_RAW} \
                --rate ${PUBLISH_RATE} \
                --max-frames ${MAX_FRAMES} \
                --warmup ${WARMUP_FRAMES} \
                --data-type bin \
                --data-path ${VEL_KITTI_REDUCED}/training/velodyne"
    [[ -n "${SINGLE_MODEL}"  ]] && args+=" --model ${SINGLE_MODEL}"
    [[ -n "${SINGLE_CONFIG}" ]] && args+=" --config ${SINGLE_CONFIG}"

    bash "$(dirname "$0")/src/lidar/tools/perf_evaluation/run_realtime_eval.sh" ${args}
}

# ─── Step 7: Generate LaTeX tables ───────────────────────────────────────────
run_latex() {
    step "Step 7: Generating LaTeX tables"
    docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "mkdir -p '${OFFLINE_LATEX}' '${ONLINE_LATEX}'"

    for variant in original downsampled; do
        local src="${OFFLINE_RAW}/${variant}"
        docker exec "${CONTAINER_OPENPCDET}" bash -c \
            "cd ${OPC_ROOT} && \
             python3 ${OPC_BATCH}/generate_latex_single_dataset.py '${src}' && \
             mv '${src}/latex/'*.tex '${OFFLINE_LATEX}/' 2>/dev/null || true"
    done

    docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "cd ${OPC_ROOT} && \
         python3 ${OPC_BATCH}/generate_latex_tables.py '${OFFLINE_RAW}/interpolated' && \
         mv '${OFFLINE_RAW}/interpolated/latex/'*.tex '${OFFLINE_LATEX}/' 2>/dev/null || true"

    docker exec "${CONTAINER_OPENPCDET}" bash -c \
        "cd ${OPC_ROOT} && \
         python3 ${OPC_TOOLS}/perf_evaluation/aggregate_realtime_results.py '${ONLINE_RAW}' && \
         cp '${ONLINE_RAW}/'*.csv '${ONLINE_LATEX}/' 2>/dev/null || true"
}

# ─── Main ─────────────────────────────────────────────────────────────────────
echo "════════════════════════════════════════════════════════"
echo " Full pipeline  —  results → ${RESULTS_HOST}"
echo "════════════════════════════════════════════════════════"

check_storage

docker exec "${CONTAINER_OPENPCDET}" bash -c \
    "mkdir -p '${OFFLINE_RAW}' '${ONLINE_RAW}' '${OFFLINE_LATEX}' '${ONLINE_LATEX}'"

${SKIP_DOWNSAMPLE} || run_downsample
${SKIP_INFOS}      || run_kitti_infos
${SKIP_INTERP}     || run_interpolation
${SKIP_OFFLINE}    || { run_offline_evals; run_save_detections; }
${SKIP_ONLINE}     || run_online_eval
run_latex

log "Pipeline complete. Results: ${RESULTS_HOST}"
