# [workspace]
# channels = [
#     # "https://prefix.dev/pixi-build-backends",
#     "https://prefix.dev/conda-forge",
#     "https://prefix.dev/robostack-humble",
#     ]
# platforms = ["linux-64"]
# preview = ["pixi-build"]

[package.build]
backend ={ name = "pixi-build-ros", version = "*"}

[package.build.config]
distro = "humble"

[package.run-dependencies]
ros-humble-foxglove-bridge = "*"
ros-humble-pcl-ros = "*"
ros-humble-velodyne = "*"
