[project]
name = "pcdet"
version = "0.1.0"
requires-python = ">=3.6, <=3.11"

[build-system] 
build-backend = "hatchling.build"
requires = ["hatchling", "setuptools"]

[tool.pixi.package] 
name = "pcdet"
version = "0.1.0"

[tool.pixi.package.build] 
backend = { name = "pixi-build-python", version = "*", channels = ["conda-forge", "https://prefix.dev/pixi-build-backends"]}

[tool.pixi.package.build-dependencies]
SharedArray = "==3.1.0"
setuptools = "*"

[tool.pixi.package.host-dependencies] 
hatchling = "*"
scikit-image = "*"
SharedArray = "==3.1.0"

[package.run-dependencies]
numpy = "*"
llvmlite = "*"
numba = "*"
tensorboardX = "*"
pyyaml = "*"
scikit-image = "*"
tqdm = "*"

#SharedArray = https://github.com/open-mmlab/OpenPCDet/issues/867#issuecomment-1075166761
SharedArray = "==3.1.0" 
visual_utils = "*"


[tool.hatch.build.targets.wheel]
packages = ["."]